# Generated by Django 4.2 on 2023-04-08 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Travel_Category')),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='Travel_Reviews')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=150)),
                ('package_image', models.ImageField(upload_to='Travel_Package')),
                ('package_duration', models.IntegerField()),
                ('package_size', models.IntegerField()),
                ('package_rating', models.IntegerField()),
                ('package_age', models.CharField(max_length=50)),
                ('package_map', models.CharField(max_length=600)),
                ('package_location', models.CharField(max_length=150)),
                ('package_vehicle', models.CharField(max_length=150)),
                ('price', models.FloatField(max_length=100)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Partner.category')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='Travel_Guide')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Partner.category')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image1', models.ImageField(upload_to='Travel_Gallery')),
                ('gallery_image2', models.ImageField(upload_to='Travel_Gallery')),
                ('gallery_image3', models.ImageField(upload_to='Travel_Gallery')),
                ('gallery_image4', models.ImageField(upload_to='Travel_Gallery')),
                ('gallery_image5', models.ImageField(upload_to='Travel_Gallery')),
                ('gallery_image6', models.ImageField(upload_to='Travel_Gallery')),
                ('gallery_image7', models.ImageField(upload_to='Travel_Gallery')),
                ('gallery_image8', models.ImageField(upload_to='Travel_Gallery')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Partner.category')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_proof', models.FileField(upload_to='Travel_Booking')),
                ('user_address', models.CharField(max_length=150)),
                ('user_state', models.CharField(max_length=150)),
                ('user_pin', models.CharField(max_length=20)),
                ('travelers', models.IntegerField()),
                ('traveler_1', models.IntegerField()),
                ('traveler_2', models.IntegerField()),
                ('starting_location', models.CharField(max_length=150)),
                ('starting_date', models.DateField()),
                ('driver', models.BooleanField()),
                ('vehicle', models.BooleanField()),
                ('insurance', models.BooleanField()),
                ('total_price', models.IntegerField()),
                ('payment_option', models.CharField(max_length=150)),
                ('payment_status', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False, help_text='0-pending,1-confirm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Partner.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=150)),
                ('blog_image', models.ImageField(upload_to='Travel_Blogs')),
                ('blog_description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Partner.category')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='Traveler_Profile')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
