# Generated by Django 4.2 on 2023-04-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Partner', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
