# Generated by Django 4.2 on 2023-04-09 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Travel_Partner', '0004_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_proof', models.FileField(upload_to='Travel_Booking')),
                ('user_address', models.CharField(max_length=150)),
                ('user_state', models.CharField(max_length=150)),
                ('user_pin', models.CharField(max_length=20)),
                ('travelers', models.IntegerField()),
                ('traveler_1', models.IntegerField()),
                ('traveler_2', models.IntegerField()),
                ('starting_location', models.CharField(max_length=150)),
                ('starting_date', models.DateField()),
                ('driver', models.CharField(max_length=10)),
                ('vehicle', models.CharField(max_length=10)),
                ('Insurance', models.CharField(max_length=10)),
                ('total_price', models.IntegerField()),
                ('payment_option', models.CharField(max_length=150)),
                ('payment_status', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False, help_text='0-pending,1-confirm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Partner.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
