# Generated by Django 4.2 on 2023-04-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Partner', '0007_alter_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
