# Generated by Django 4.2 on 2023-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Partner', '0008_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
