# Generated by Django 4.2 on 2023-04-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Partner', '0009_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
